name: Unit Tests

on:
  push:
    branches:
      - main
      - develop
      - ci/cd
  pull_request:
    branches: [ main, develop, ci/cd ]

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/Hydrogen

      - name: Install dependencies
        run: npm install
      
      - name: Run build command
        run: npm run build